CREATE OR REPLACE TRIGGER Cascade_Delete_Students
BEFORE DELETE ON GROUPS
FOR EACH ROW
BEGIN
    DELETE FROM STUDENTS WHERE GROUP_ID = :OLD.ID;
    EXCEPTION
    WHEN OTHERS THEN
                NULL;
END;

CREATE OR REPLACE TRIGGER Insert_Studens_Foreign_Key
BEFORE INSERT ON STUDENTS
FOR EACH ROW
DECLARE
    v_count INT;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM GROUPS
    WHERE GROUPS.ID = :NEW.GROUP_ID;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Группы с таким ID не существует');
    END IF;
END;